In [11]:
import os
import pandas as pd
from IPython.display import display

# 1. Menentukan nama/lokasi file
file_path = "klasifikasimhs.csv"

# 2. Memeriksa ketersediaan file dan membacanya
if os.path.exists(file_path):
    df = pd.read_csv(file_path)
    print("Dataset berhasil dibaca!\n")
    
    # 3. Menjalankan kode ringkasan yang Anda buat sebelumnya
    nama_dataset = file_path
    ringkasan = pd.DataFrame({
        "Informasi": [
            "Nama Dataset",
            "Jumlah Baris",
            "Jumlah Kolom",
            "Jumlah Data Kosong",
            "Jumlah Baris Duplikat",
            "Jumlah Kolom Numerik",
            "Jumlah Kolom Kategorikal"
        ],
        "Hasil": [
            nama_dataset,
            df.shape[0],
            df.shape[1],
            df.isnull().sum().sum(),
            df.duplicated().sum(),
            df.select_dtypes(include="number").shape[1],
            df.select_dtypes(include="object").shape[1]
        ]
    })
    
    display(ringkasan)

else:
    print("File tidak ditemukan. Periksa lokasi dataset.")

Dataset berhasil dibaca!

C:\Users\Ibnu Syina\AppData\Local\Temp\ipykernel_21620\424094295.py:32: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.select_dtypes(include="object").shape[1]

                  Informasi               Hasil
0              Nama Dataset  klasifikasimhs.csv
1              Jumlah Baris                 100
2              Jumlah Kolom                   6
3        Jumlah Data Kosong                   0
4     Jumlah Baris Duplikat                  77
5      Jumlah Kolom Numerik                   4
6  Jumlah Kolom Kategorikal                   2

In [12]:
# Nama file dataset
file_path = "klasifikasimhs.csv"

# Memeriksa apakah file tersedia
if os.path.exists(file_path):
    df = pd.read_csv(file_path)
    print("Dataset berhasil dibaca!")
else:
    print("File tidak ditemukan. Periksa lokasi dataset.")

Dataset berhasil dibaca!

In [13]:
# Informasi dataset
nama_dataset = "Klasifikasi Mahasiswa"
sumber_dataset = "Isi dengan sumber asli dataset"
lisensi_dataset = "Belum diketahui"

print("Nama Dataset :", nama_dataset)
print("Sumber       :", sumber_dataset)
print("Lisensi      :", lisensi_dataset)

Nama Dataset : Klasifikasi Mahasiswa
Sumber       : Isi dengan sumber asli dataset
Lisensi      : Belum diketahui

In [14]:
# Menampilkan 5 baris pertama
display(df.head())

,Tempat Tinggal,Pekerjaan Orang Tua,Penghasilan Orang Tua,Jumlah Tanggungan Orang Tua,Kendaraan,Kelayakan Keringanan UKT
0,0,PNS,10000000,3,1,0
1,0,TNI/POLRI,8000000,2,2,1
2,1,Petani,4000000,4,0,0
3,1,Nelayan,3000000,5,1,0
4,0,Buruh,2000000,2,1,1

In [15]:
# Menampilkan 5 baris akhir
display(df.tail())

,Tempat Tinggal,Pekerjaan Orang Tua,Penghasilan Orang Tua,Jumlah Tanggungan Orang Tua,Kendaraan,Kelayakan Keringanan UKT
95,0,PNS,9000000,2,2,1 1
96,1,Wiraswasta,6000000,1,1,1
97,1,TNI/POLRI,8000000,2,2,1
98,0,Nelayan,3000000,5,1,0
99,0,Petani,700000,3,1,0

In [16]:
jumlah_baris, jumlah_kolom = df.shape

print("Jumlah baris  :", jumlah_baris)
print("Jumlah kolom  :", jumlah_kolom)
print("Total data    :", df.size)

Jumlah baris  : 100
Jumlah kolom  : 6
Total data    : 600

In [17]:
print("Nama Kolom:")
print(df.columns.tolist())

print("\nTipe Data Setiap Kolom:")
print(df.dtypes)

Nama Kolom:
['Tempat Tinggal', 'Pekerjaan Orang Tua', 'Penghasilan Orang Tua', 'Jumlah Tanggungan Orang Tua', 'Kendaraan', 'Kelayakan Keringanan UKT']

Tipe Data Setiap Kolom:
Tempat Tinggal                 int64
Pekerjaan Orang Tua              str
Penghasilan Orang Tua          int64
Jumlah Tanggungan Orang Tua    int64
Kendaraan                      int64
Kelayakan Keringanan UKT         str
dtype: object

In [19]:
df.info()  # lanjutan atasnya

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 6 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Tempat Tinggal               100 non-null    int64
 1   Pekerjaan Orang Tua          100 non-null    str
 2   Penghasilan Orang Tua        100 non-null    int64
 3   Jumlah Tanggungan Orang Tua  100 non-null    int64
 4   Kendaraan                    100 non-null    int64
 5   Kelayakan Keringanan UKT     100 non-null    str
dtypes: int64(4), str(2)
memory usage: 5.7 KB

In [20]:
# Menghitung jumlah data kosong setiap kolom
data_kosong = df.isnull().sum()

print("Jumlah Data Kosong per Kolom:")
print(data_kosong)

print("\nTotal Data Kosong:", df.isnull().sum().sum())

Jumlah Data Kosong per Kolom:
Tempat Tinggal                 0
Pekerjaan Orang Tua            0
Penghasilan Orang Tua          0
Jumlah Tanggungan Orang Tua    0
Kendaraan                      0
Kelayakan Keringanan UKT       0
dtype: int64

Total Data Kosong: 0

In [21]:
persentase_kosong = (df.isnull().sum() / len(df)) * 100

hasil_missing = pd.DataFrame({
    "Jumlah Data Kosong": df.isnull().sum(),
    "Persentase (%)": persentase_kosong
})

display(hasil_missing)

                             Jumlah Data Kosong  Persentase (%)
Tempat Tinggal                                0             0.0
Pekerjaan Orang Tua                           0             0.0
Penghasilan Orang Tua                         0             0.0
Jumlah Tanggungan Orang Tua                   0             0.0
Kendaraan                                     0             0.0
Kelayakan Keringanan UKT                      0             0.0

In [22]:
# Statistik deskriptif untuk semua kolom
display(df.describe(include="all").T)

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
Tempat Tinggal,100.0,NaN,NaN,NaN,0.5,0.502519,0.0,0.0,0.5,1.0,1.0
Pekerjaan Orang Tua,100,8,Ibu Rumah Tangga,18,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Penghasilan Orang Tua,100.0,NaN,NaN,NaN,5427000.0,2533128.181486,700000.0,3000000.0,5500000.0,8000000.0,10000000.0
Jumlah Tanggungan Orang Tua,100.0,NaN,NaN,NaN,2.59,1.129002,1.0,2.0,2.0,3.25,5.0
Kendaraan,100.0,NaN,NaN,NaN,1.07,0.655282,0.0,1.0,1.0,1.25,2.0
Kelayakan Keringanan UKT,100,3,1,64,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [23]:
jumlah_duplikat = df.duplicated().sum()

print("Jumlah baris duplikat:", jumlah_duplikat)

Jumlah baris duplikat: 77

In [24]:
for kolom in df.columns:
    print(f"\nKolom: {kolom}")
    print("Jumlah nilai unik:", df[kolom].nunique())
    print("Contoh nilai:", df[kolom].unique()[:10])

Kolom: Tempat Tinggal
Jumlah nilai unik: 2
Contoh nilai: [0 1]

Kolom: Pekerjaan Orang Tua
Jumlah nilai unik: 8
Contoh nilai: <ArrowStringArray>
[             'PNS',        'TNI/POLRI',           'Petani',
          'Nelayan',            'Buruh', 'Ibu Rumah Tangga',
       'Wiraswasta',             'Guru']
Length: 8, dtype: str

Kolom: Penghasilan Orang Tua
Jumlah nilai unik: 10
Contoh nilai: [10000000  8000000  4000000  3000000  2000000  5000000  9000000  6000000
  7000000   700000]

Kolom: Jumlah Tanggungan Orang Tua
Jumlah nilai unik: 5
Contoh nilai: [3 2 4 5 1]

Kolom: Kendaraan
Jumlah nilai unik: 3
Contoh nilai: [1 2 0]

Kolom: Kelayakan Keringanan UKT
Jumlah nilai unik: 3
Contoh nilai: <ArrowStringArray>
['0', '1', '1 1']
Length: 3, dtype: str

In [25]:
ringkasan = pd.DataFrame({
    "Informasi": [
        "Nama Dataset",
        "Jumlah Baris",
        "Jumlah Kolom",
        "Jumlah Data Kosong",
        "Jumlah Baris Duplikat",
        "Jumlah Kolom Numerik",
        "Jumlah Kolom Kategorikal"
    ],
    "Hasil": [
        nama_dataset,
        df.shape[0],
        df.shape[1],
        df.isnull().sum().sum(),
        df.duplicated().sum(),
        df.select_dtypes(include="number").shape[1],
        df.select_dtypes(include="object").shape[1]
    ]
})

display(ringkasan)

C:\Users\Ibnu Syina\AppData\Local\Temp\ipykernel_21620\3464697519.py:18: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.select_dtypes(include="object").shape[1]

                  Informasi                  Hasil
0              Nama Dataset  Klasifikasi Mahasiswa
1              Jumlah Baris                    100
2              Jumlah Kolom                      6
3        Jumlah Data Kosong                      0
4     Jumlah Baris Duplikat                     77
5      Jumlah Kolom Numerik                      4
6  Jumlah Kolom Kategorikal                      2